return {
    donor_material_enabled = false,
    donor_material = "units/beings/player/dark_pact_skins/skaven_wind_globadier/skin_1001/third_person/mtr_outfit",
    donor_package = "units/beings/player/dark_pact_skins/skaven_wind_globadier/skin_1001/third_person/chr_third_person_mesh",
    donor_texture_shadow = false,
    donor_texture_shadow_package = false,
    enabled = false,
    hero_preview_enabled = false,
    hide_donor_weapons = false,
    locomotion_events_enabled = false,
    manual_clip_length = 0.8,
    manual_clip_name = "units/pusfume/anims/pusfume_3p_walk",
    manual_clip_probe = false,
    manual_skin_probe = false,
    parent_child_material = false,
    parent_child_package = false,
    whisker_child_material = false,
    whisker_donor_package = false,
    root_animation_isolation = false,
    skin_name = "pusfume_skin",
    third_person_unit = "units/pusfume/pusfume_3p",
}
